### ISSUE TITLE
Extract common library from Exasol Virtual Schema Lua

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-virtual-schema-common-lua#1]
## Situation

We need the common part of EVSL and RLSL in a separate library to avoid code duplication.

```[tasklist]
## Tasks
- [x] Common parts extracted (details see below)
- [x] Tests extracted (details see below)
- [x] Build
```

## What Goes Where?

Lua Source files to be moved:

- [x] `validator.lua`: VSCL
- [x] `AbstractMetadataReader.lua`: EVSCL
- [x] `adapter_capabilities.lua`: no change
- [x] `ExasolAdapter.lua`: no change
- [x] `LocalMetadataReader.lua`: EVSCL
- [x] ` MetadataReaderFactory.lua`: no change
- [x] ` RemoteMetadataReader.lua` no change
- [x] `AbstractQueryRewriter.lua`: EVSCL
- [x] `ConnectionReader.lua`: no change
- [x] `ExasolAdapterProperties.lua`: EVSCL (but `CONNECTION` property only valid for EVSL)
- [x] `LocalQueryRewriter.lua`: EVSCL
- [x] `QueryRewriterFactory.lua`: no change
- [x] `RemoteQueryRewriter.lua`: no change

Unit tests must be moved accordingly
