### ISSUE TITLE
Prepare EVSCL for release on Luarocks

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-virtual-schema-common-lua#3]
## Situation

To use it as a proper base library, EVSCL needs to be available through Luarocks.

```[tasklist]
### Tasks
- [x] Get a unique namespace (`exasol.evscl`)
- [x] Fix requirement trace
- [x] Remove RLS-specific code
```

# Acceptance Criteria

* EVSCL available through Luarocks

**Comment by redcatbear** [comment]
Release: https://luarocks.org/modules/exasol/exasol-virtual-schema-common-lua/1.0.0-1
